import React, { useState, useEffect } from 'react'
import { Switch, Route, Link } from 'react-router-dom'
import defaultProfilePicture from '../../assets/images/pexels-andrea-piacquadio-3765114.jpg'
import AutoGeneratedImage from '../../components/profile/AutoGeneratedImage'
import UserConfigurationPage from './UserSubPages/UserConfigurationPage'
import UserNotificationPage from './UserSubPages/UserNotificationPage'
import UserStatisticsPage from './UserSubPages/UserStatisticsPage'


export const UserPage = ({ getUserInfo }) => {
  const [user, setUser] = useState({
    profilePicture: '',
    username: '',
    email: '',
    course: '',
    year: ''
  })

  const handleGetUserInfo = React.useCallback(async () => {
    try {
      const response = await getUserInfo()
      setUser(response.data.user)
    } catch (error) {
      console.error(error)
    }
  }, [getUserInfo])

  useEffect(() => {
    handleGetUserInfo()
  }, [handleGetUserInfo])

  return (
    <div className="user-profile-main-container">
      <div className="user-profile-header-container">
        <div className="image-container">
          {user.profilePicture === '' || user.profilePicture === undefined ?
            <AutoGeneratedImage
              username={user.username !== '' ? user.username : user.email}
            /> : (
              <img srcSet={(user.profilePicture === '' || user.profilePicture !== '') ? defaultProfilePicture : user.profilePicture} alt="" className="user-image" />
            )}



          <div className="change-image-container">
            <h3 className="change-image-text">Alterar de imagem</h3>
          </div>
        </div>
        <div className="user-info-container">
          <h1 className="user-important-info">{user.username}</h1>
          <p className="user-other-info">{user.course}</p>
          <p className="user-other-info">{user.year}</p>
        </div>
      </div>
 
      <ul className="user-profile-menu">
        <Link className="user-profile-menu-item" to="/user/statistics">
          Estatísticas
        </Link>
        <Link className="user-profile-menu-item" to="/user/configuration">
          Configurações
        </Link>
      </ul>

      <Switch>
        <Route exact path="/user/notifications">
          <UserNotificationPage></UserNotificationPage>
        </Route>
        <Route exact path="/user/statistics">
          <UserStatisticsPage></UserStatisticsPage>
        </Route>
        <Route exact path="/user/configuration">
          <UserConfigurationPage></UserConfigurationPage>
        </Route>
      </Switch>
    </div>
  )
}
